services:
  data:
    image: mariadb:latest
    container_name: data
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./src:/docker-entrypoint-initdb.d
    networks:
      - tp3-net

  script:
    build:
      context: ./php
    container_name: script
    environment:
      - DB_HOST=data
      - DB_USER=root
      - DB_PASS=${MARIADB_ROOT_PASSWORD}
      - DB_NAME=mabase
    volumes:
      - ./src:/app
    networks:
      - tp3-net
    depends_on:
      - data
    command: sh -c "sleep 15 && php-fpm"

  http:
    image: nginx:1.27
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tp3-net
    depends_on:
      - script

networks:
  tp3-net:
